### ISSUE TITLE
Swift3 Alamofire pod dependence XCode8 beta 6

### ISSUE THREAD

**Issue by jmbeneUF** [Alamofire/AlamofireNetworkActivityIndicator#13]
Please update .podspecs for swift3 branch as I am having problems using the Podfile:

```
pod 'Alamofire',                            :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'
pod 'AlamofireNetworkActivityIndicator',    :git => 'https://github.com/Alamofire/AlamofireNetworkActivityIndicator.git', :branch => 'swift3'
```

Updating pods with CocoaPods 1.1.0.beta.1 returns the next error:
- `Alamofire (= 4.0.0-beta.1)` required by `AlamofireNetworkActivityIndicator (2.0.0-beta.1)`

It tries to build the Alamofire version 4.0.0-beta.2

Thanks,

**Comment by cnoon** [comment]
This has all been resolved. We've just released Alamofire 4, AlamofireImage 3, and AlamofireNetworkActivityIndicator 2.

Cheers. 🍻
