### ISSUE TITLE
Spinner can be left up indefinitely

### ISSUE THREAD

**Issue by graham-perks-snap** [Alamofire/AlamofireNetworkActivityIndicator#14]
The indicator works great. However there's a threading issue in decrementActivityCount().

This has a line:

    guard activityCount > 0 else { return }

To prevent the activityCount going negative. (I'm curious why this line was introduced.) I have a situation where the activityCount would go negative. The debugger hits the `else` part of the guard. I believe the timing hole is around AlamoFire's resume() method.

AlamoFire's Request.resume() method (I added the comments):

    public func resume() {
        if startTime == nil { startTime = CFAbsoluteTimeGetCurrent() }

        task.resume()

        // TIMING HOLE HERE. 
        // The task comes back fast (e.g. from cache) before we call postNotificationName. 
        // The decrement is called in the result callback, and activityCount should go to -1. (But doesn't due to the guard > 0)
        // Then this thread resumes and posts its notification about the task starting.
        // Now the activity indicator's count is 1... forever above zero, so the indicator stays on.
        NSNotificationCenter.defaultCenter().postNotificationName(Notifications.Task.DidResume, object: task)
    }

I see no reason for the `guard activityCount > 0` line. Removing it would fix this hole.

**Comment by cnoon** [comment]
Hi @graham-perks-snap,

I'll need to get back to you on this. I can't give you a good reason as to why the cap is there. Will need to investigate further. Hang tight.

**Comment by graham-perks-snap** [comment]
Thanks, I understand you're a little busy with releases!

This problem shows when kicking off several concurrent requests, e.g. fetching live data for table rows as the user quickly scrolls new cells into view. IIRC I've also seen it when calls to AlamoFireImage's ImageDownloader.defaultInstance.downloadImages() is given many URLs.

**Comment by gereons** [comment]
I'm seeing the same symptoms, albeit not caused by that `guard`, when using SwiftyDropbox - on an otherwise idle system, when all Dropbox API requests are done, `activityCount` remains at 1.

**Comment by cnoon** [comment]
Thanks for all the feedback here @graham-perks-snap and @gereons. I just pushed up 3bcb6917 to address the issue by removing the `guard`. This should go out in an official release here shortly.

Cheers. 🍻
