### ISSUE TITLE
Runloop is not thread-safe

### ISSUE THREAD

**Issue by langyanduan** [Alamofire/AlamofireNetworkActivityIndicator#16]
It seem the lib add `Timer` to `Runloop.main` in network thread (generally not main thread).
But the document **warning** [NSRunLoop](https://developer.apple.com/reference/foundation/nsrunloop) is not thread safe.
>
The NSRunLoop class is generally not considered to be thread-safe and its methods should only be called within the context of the current thread. You should never try to call the methods of an NSRunLoop object running in a different thread, as doing so might cause unexpected results.

[Core Foundation are generally thread-safe](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/RunLoopManagement/RunLoopManagement.html#//apple_ref/doc/uid/10000057i-CH16-SW26), use `CFRunLoop*` may be better.

**Comment by cnoon** [comment]
Good catch @langyanduan. I've just pushed up 0f6bc518 which addresses the issue. This change will go out in a release here shortly.

Thanks again! 🍻
