### ISSUE TITLE
Swift 3.0.1: Carthage/Checkouts/Alamofire/Source/Request.swift:474:47: warning: expression implicitly coerced from 'URLSessionTask?' to Any

### ISSUE THREAD

**Issue by racer1988** [Alamofire/AlamofireNetworkActivityIndicator#18]
Same as https://github.com/Alamofire/Alamofire/issues/1745

Carthage build on Xcode 8.1 Swift 3.0.1 produces warnings:
Carthage/Checkouts/Alamofire/Source/Request.swift:474:47: warning: expression implicitly coerced from 'URLSessionTask?' to Any

**Comment by cnoon** [comment]
Hi @racer1988,

This issue has been resolved in the Alamofire 4.1.0 release.

Cheers. 🍻
