### ISSUE TITLE
minimum deployment target

### ISSUE THREAD

**Issue by DarkwingXL** [Alamofire/AlamofireNetworkActivityIndicator#22]
Hello,
When I'm trying to install the pod I got error:
"Specs satisfying the `AlamofireNetworkActivityIndicator (~> 2.0)` dependency were found, but they required a higher minimum deployment target."

But now AlamofireNetworkActivityIndicator requirements is:
"iOS 8.0+
Xcode 8.0+
Swift 3.0+"
Alamofire 4.1 requirements is the same now and I successfully install Alamofire 4.1 via CocoaPods with "platform :ios, '8.0'" setting (in the Podfile and XCode project deployment target too) but I can't install AlamofireNetworkActivityIndicator with these correct settings.

**Comment by cnoon** [comment]
The latest AFNAI 2.1.0 release supports an iOS 8.0 deployment target along with AF 4.1.0. These can be used in conjunction.
