### ISSUE TITLE
Siesta + custom alamofire provider + AlamofireNetworkActivityIndicator stucks forever

### ISSUE THREAD

**Issue by piv199** [Alamofire/AlamofireNetworkActivityIndicator#23]
I don't know why, but there are lots of times when executing request through alamofire using Siesta framework, alamofire start request called twice while alamofire did finish request called only once. 

Have anybody the same behaviour?

**Comment by cnoon** [comment]
I would suggest filing an issue with Siesta @piv199. There's nothing we can do here directly.
