### ISSUE TITLE
network indicator disappear during upload

### ISSUE THREAD

**Issue by tirrorex** [Alamofire/AlamofireNetworkActivityIndicator#26]
Hi, so during an upload of multipartformdata, the NetworkActivityIndicator disappear, usually between 7 to 15% of the upload completion.
Is there a way to fix this?
I use the version 2.2.0 of the framework which is installed with cocoapods.
Swift 3.1 with xcode 8.3.3

**Comment by cnoon** [comment]
Hi @tirrorex,

Apologies for this ticket sitting open for this long unanswered. We just pushed out AFNAI 3.0.0-beta.1 with some big updates to the activity tracking that most likely will resolve this issue. If you would still be willing, we would certainly be interested if you still can produce this issue.

I'm going to close this issue out for now, and will happily re-open if there seems to still be an issue with the 3.0.0-beta.1 release.

Cheers. 🍻
