### ISSUE TITLE
Swift4 Package Manger

### ISSUE THREAD

**Issue by MahranBayed** [Alamofire/AlamofireNetworkActivityIndicator#27]
Cant build using swift package manger
`error: package has unsupported layout; found loose source files: .build/checkouts/AlamofireNetworkActivityIndicator.git--6721799582381667356/Tests/NetworkActivityIndicatorManagerTests.swift`

**Comment by jshier** [comment]
SPM doesn't actually support building anything but macOS or Linux frameworks or executables. I think I should just remove SPM support for now, until they get around allowing it to build for iOS.

**Comment by MainasuK** [comment]
Manually SPM integrate is possible:
https://github.com/j-channings/swift-package-manager-ios

Hope add Package.swift for this repo.
