### ISSUE TITLE
Activity Indicator Not Working

### ISSUE THREAD

**Issue by tinu22** [Alamofire/AlamofireNetworkActivityIndicator#29]
I am using alamofire to call API. For Activity Controller I am installed this pod. In `AppDelegate` I import `AlamofireNetworkActivityIndicator` and in `didFinishLaunchingWithOptions` I wrote `NetworkActivityIndicatorManager.shared.isEnabled = true`. But when  API is called from Alamofire the Indicator is not shown. Please let me know what wrong I have done?

**Comment by ControlAdad** [comment]
Not displaying in my app, too.
iOS 11, iPhone 7.

**Comment by bcorrea2-luizalabs** [comment]
@tinu22 maybe your API request is too fast, try to change `startDelay` to `0` to test...

**Comment by igorpakushin** [comment]
@bcorrea2-luizalabs, it's wired to me it defaults to 1.0, for the simplest use cases it will never be shown with a delay this long! For others, here's a fix:

```
NetworkActivityIndicatorManager.shared.startDelay = 0
```
