### ISSUE TITLE
Separate AlamofireNetworkActivityIndicator from Alamofire?

### ISSUE THREAD

**Issue by benasher44** [Alamofire/AlamofireNetworkActivityIndicator#32]
Hi there! We were able to use `AlamofireNetworkActivityIndicator` without `Alamofire` by just removing the notification registration methods. I'd love to figure out a way to expose this class as its own framework in such a way that `Alamofire` users could still use this seamlessly as they do today, but folks like us could install a subspec that didn't require `Alamofire`. I'd be open to doing the work here too. Thanks!

**Comment by jshier** [comment]
Thanks for the offer! Sure, if you can make the changes without affect current consumers, we'd be glad. I just merged a big infrastructure PR, so make sure you rebase from current master.

**Comment by benasher44** [comment]
In Swift 4.1, doing this gets a lot easier because we can use `#if canImport(Alamofire)` to guard against using the notification symbols in projects that don't use `Alamofire`, so I think I'll wait for that.

**Comment by jessesquires** [comment]
@benasher44 Nice 😎

**Comment by jshier** [comment]
@benasher44 I've updated to 2.2.1 for Swift 4.1, so you can begin when you want. However, I'm not sure we can ship a release that requires Swift 4.1 until we can finish and release Alamofire 5, which will require that version.

**Comment by benasher44** [comment]
Sounds good! I’ll try to get a PR up soon that requires Swift 4.1. That route I think will have the cleanest final API, and then we can wait until Alamofire 5 lands to merge it.

**Comment by benasher44** [comment]
Closing. See note about why in #34.
