### ISSUE TITLE
Push to Cocoapod and update README

### ISSUE THREAD

**Issue by Laptopmini** [Alamofire/AlamofireNetworkActivityIndicator#36]
* Release 2.2.1 has not yet been pushed to Cocoapod (https://cocoapods.org/pods/AlamofireNetworkActivityIndicator)
* README has (now) outdated requirements. (https://github.com/Alamofire/AlamofireNetworkActivityIndicator#requirements)

Hotfix:
```
pod 'AlamofireNetworkActivityIndicator', :git => 'https://github.com/Alamofire/AlamofireNetworkActivityIndicator.git', :tag => '2.2.1'
```

**Comment by jshier** [comment]
Sorry, this has been pushed now. Thanks for letting us know!
