### ISSUE TITLE
ActivityCount goes below 0 preventing the ActivityIndicator to show up

### ISSUE THREAD

**Issue by jklapwyk** [Alamofire/AlamofireNetworkActivityIndicator#38]
## What did you do?

I was using the AlamofireImage swift library to download image thumbnails for a table view. I was also using **this** library to show the user network usage during the thumbnail downloading process. 

## What did you expect to happen?

Whenever a image thumbnail was being downloaded the network activity indicator would show up.

## What happened instead?

Normally the activity indicator does show up, however when I scroll down the table view quickly, the activity indicator will no longer show up. 

Further debugging I found that the `activityCount` in the `NetworkActivityIndicatorManager` would actually go in the negatives.

I found that there were more notifications calls `Notification.Name.Task.DidComplete` than the corresponding `Notification.Name.Task.DidResume`.

My suspicions are that when scrolling quickly through the list, the `AlamofireImage` library will eventually queue up the network requests as the `maximumActiveDownloads` limit has been reached. And because the cell which has an image that has been queued may not even start the download network request before it gets cancelled, as the cell is being recycled,  the `Notification.Name.Task.DidComplete` gets called for the request, but it never did send the `Notification.Name.Task.DidResume` as it never got started.

The issue may in fact lie in the AlamofireImage library but wanted to bring it up here as the issue is noticeable with this library.

## Example log

```
...
networkRequestDidStart = -9
networkRequestDidComplete = -10
networkRequestDidComplete = -11
networkRequestDidComplete = -12
networkRequestDidComplete = -13
networkRequestDidStart = -12
networkRequestDidStart = -11
networkRequestDidComplete = -12
networkRequestDidComplete = -13
networkRequestDidStart = -12
networkRequestDidComplete = -13
networkRequestDidStart = -12
networkRequestDidComplete = -13
...
```

## Alamofire Environment

- Xcode (9.4.1)
- Mac OSX (10.13.5)
- Swift 4.1
- Devices running iOS 11+
- Alamofire (4.7.2)
- AlamofireImage (3.3.1)
- AlamofireNetworkActivityIndicator (2.2.1)

## Demo Project

Here's a link to a very basic project that should highlight the problem. I found the negative `activityCount` by adding print statements around the lines in the `NetworkActivityIndicatorManager`:

```
@objc private func networkRequestDidStart() {
        incrementActivityCount()
        print("networkRequestDidStart = \(activityCount)")
    }

    @objc private func networkRequestDidComplete() {
        decrementActivityCount()
        print("networkRequestDidComplete = \(activityCount)")
    }
```

[GitHub Project](https://github.com/jklapwyk/activityIndicator)

**Comment by jshier** [comment]
Thanks for the detailed report! It looks like this will be a bit complex to fix, as we may need to refactor to track resume / (finish / cancel) pairs. It may be a while before we get to it, so would you be able to take a look, since you're already familiar? My guess is that we may need to track the `URLSessionTask.taskIdentifier` or we may be able to get away with not counting start / finish events when the notification has no task in the `userInfo`.

**Comment by cnoon** [comment]
Issue has been resolved in the redesign of the activity count tracking in the 3.0.0-beta.1 release.

Cheers. 🍻

**Comment by jklapwyk** [comment]
That is great news!
