### ISSUE TITLE
Do i need to set a GUI?

### ISSUE THREAD

**Issue by fboulegue** [Alamofire/AlamofireNetworkActivityIndicator#4]
do i have to set a gui for this, or does is simply set it in center?

**Comment by cnoon** [comment]
The [network activity indicator](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Controls.html#//apple_ref/doc/uid/TP40006556-CH15-SW44) will appear in the top left of the status bar.

**Comment by fboulegue** [comment]
ah thanks, i thought you could use it for a custom activity indicator inside of your view.
