### ISSUE TITLE
Carthage compilation error with Xcode 10.2

### ISSUE THREAD

**Issue by Serahug** [Alamofire/AlamofireNetworkActivityIndicator#43]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireNetworkActivityIndicator/blob/master/CONTRIBUTING.md).

## What did you do?

Xcode 10.2

carthage bootstrap --platform iOS

## What did you expect to happen?

Install AlamofireNetworkActivityIndicator from Carthage package manager

## What happened instead?

```
Build Failed
Task failed with exit code 65:

Build system information
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'AlamofireNetworkActivityIndicator')

** ARCHIVE FAILED **
```

## Alamofire Environment

**Alamofire version: 4.8.1**
**AlamofireNetworkActivityIndicator: 2.3.0**
**Xcode version: 10.2 (10E125)**
**Swift version: Swift 4.0 4.2 5.0**
**macOS version running Xcode: 10.14.3**

**Comment by rzulkoski** [comment]
+1, I am experiencing this as well.

**Comment by itruf** [comment]
New release 2.3.1 is required to be able to build Carthage and protect specific version of package.

**Comment by vijay2pvk** [comment]
I am also getting the same error. When can we expect a new release?

**Comment by jshier** [comment]
2.4.0 has been released to fix this issue. Thanks for your patience. Cheers! 🍻
