### ISSUE TITLE
unsupported Swift 3.0

### ISSUE THREAD

**Issue by shinma** [Alamofire/AlamofireNetworkActivityIndicator#46]
I cannot build it with Carthage because Xcode 10.2 doesn't support Swift 3.X. Could you upgrade it to minimum Swift 4.0 at least.

`SWIFT_VERSION = 3.0;`

**Comment by Serahug** [comment]
Duplicated #43

**Comment by rzulkoski** [comment]
@jshier indicated there would be a new release this week that includes the upgrade to Swift 4.0. In the meantime you can point at the `master` branch.

You can see his comments on #44.

**Comment by jshier** [comment]
2.4.0 has been released to address this issue. Thanks for your patience! Cheers! :beers:
