### ISSUE TITLE
NetworkActivityIndicatorManager crashes when registering notifications

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [Alamofire/AlamofireNetworkActivityIndicator#5]
Hello, 

I'm currently trying the AlamofireNetworkActivityIndicator version 1.1.0  with Alamofire 3.4.0. 
When I try to launch my App it constantly crashes with an EXC_BREAKPOINT when the NetworkIndiciatorManager is trying to add an observer for a notification. 

<img width="1165" alt="screen shot 2016-05-28 at 21 48 52" src="https://cloud.githubusercontent.com/assets/3126229/15629616/024aefa2-251e-11e6-9714-ef593134a035.png">

<img width="457" alt="screen shot 2016-05-28 at 21 50 12" src="https://cloud.githubusercontent.com/assets/3126229/15629623/2af4a4de-251e-11e6-9c8d-155ae35cef1b.png">

**Comment by cnoon** [comment]
Hmmmm...not sure off the top of my head as to what's going on here. Any chance you could provide a sample app that demonstrates the issue? What does your `didFinishLaunchingWithOptions` method look like? How did you import the frameworks?

**Comment by cnoon** [comment]
I'm going to close this issue out for now @Sn0wfreezeDev. If you end up providing more info to go off of, we'll happily re-open and investigate further.

Cheers. 🍻
