### ISSUE TITLE
Carthage Build Error with Swift 5

### ISSUE THREAD

**Issue by leonhelg5** [Alamofire/AlamofireNetworkActivityIndicator#57]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireNetworkActivityIndicator/blob/master/CONTRIBUTING.md).

## What did you do?

I am migrating a custom NetworkFoundation that is based on Alamofire to Swift 5.

"carthage update" (to alamofire 5.0.0-beta.5)-> success
build in Xcode -> success

"carthage build --no-skip-current" -> error

## What did you expect to happen?

The framework to build to then archive it with "carthage archive".

## What happened instead?

*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire macOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
*** Building scheme "MyNetworkFoundation" in MyNetworkFoundation.xcodeproj
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
"Task failed with exit code 65."

In the logfile this is stated:
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Alamofire iOS') ** ARCHIVE FAILED **

What confuses me is that in my project under "Build Settings" the Swift version is set to 5. When I check in "/MyNetworkFoundation/Carthage/Checkouts/Alamofire/Alamofire.xcodeproj", the Swift version of all targets of is set to 5 too. I cannot spot Swift 3 anywhere in my framework nor Alamofire.

## Alamofire Environment

**Alamofire version: 5.0.0-beta.5**
**AlamofireNetworkActivityIndicator: -**
**Xcode version: 10.2.1**
**Swift version: 5.0**
**macOS version running Xcode: 10.14.5**

**Comment by henrysaintjuste** [comment]
@leonhelg5 Did you solve this yet? I feel like I am running into a similar issue.

**Comment by leonhelg5** [comment]
Indeed, I had a nested Cartfile somewhere in the project. This messed everything up and created the conflicts.
