### ISSUE TITLE
App Crashed when integrating

### ISSUE THREAD

**Issue by lalkrishna** [Alamofire/AlamofireNetworkActivityIndicator#58]
## What did you do?

Imported AlamofireNetworkActivityIndicator using carthage, and included

> NetworkActivityIndicatorManager.shared.isEnabled = true

 in appdelegate.
Gives me 

>  1 commandlineflags.cc:1026] Ignoring RegisterValidateFunction() for flag pointer 0x10146ed98: no flag found at that address

## What did you expect to happen?

Running smoothly 

## What happened instead?

App get crashed

## Alamofire Environment

**Alamofire version:** 5.0.0-beta.5
**AlamofireNetworkActivityIndicator:** 2.4.0
**Xcode version:** 10.2.1
**Swift version:** 5
**macOS version running Xcode:**  10.14.3

**Comment by jshier** [comment]
This doesn't seem to have anything to do with AlamofireNetworkActivityIndicator.
