### ISSUE TITLE
Cannot call from an objective-c class

### ISSUE THREAD

**Issue by grundid** [Alamofire/AlamofireNetworkActivityIndicator#6]
Hi.

I have a mixed app with swift and obj-c code. My AppDelegate is still in obj-c, so I tried to init the network indicator from obj-c. This does not work.

The generated "NetworkActivityIndicatorManager-Swift.h" file does not contain the class definition. I think this is because NetworkActivityIndicatorManager does not extend from NSObject.

I have created a small helper class in Swift:

```
import Foundation
import AlamofireNetworkActivityIndicator

class SwiftHelper : NSObject {

    func initNetworkIndicator()  {
        NetworkActivityIndicatorManager.sharedManager.isEnabled = true
    }
}
```

This class I can call from obj-c code. Is it possible to extend NetworkActivityIndicatorManager from NSObject?

**Comment by cnoon** [comment]
Hi @grundid,

I'm glad you found a workaround. We're trying to avoid coupling to Objective-C any more than we need to in any of our Alamofire libraries. Therefore, we'd prefer not to inherit from `NSObject`. Since you've found a sufficient workaround, I'd continue to use that approach.

Cheers. 🍻

**Comment by grundid** [comment]
Hi!

I have also found out that annotating the NetworkActivityIndicatorManager class with @objc could also do the trick. However I was unable to test it. 
Maybe this could be a better solution??
