### ISSUE TITLE
xCode 11 fails to archive the app

### ISSUE THREAD

**Issue by furiosFast** [Alamofire/AlamofireNetworkActivityIndicator#60]
I have a problem when archiving my app, xcode remains blocked during the creation of the AlamofireNetworkActivityIndicator framework

**Comment by artemkalinovsky** [comment]
I have same issue:(

@furiosFast how did you solve it?

**Comment by furiosFast** [comment]
hi, 
in the end I discovered that the fault was of another library: SwiftSoup
