### ISSUE TITLE
Can't install AlamofireNetworkActivityIndicator

### ISSUE THREAD

**Issue by lupyana** [Alamofire/AlamofireNetworkActivityIndicator#62]
## What did you do?

Specified the package version by adding ``` pod 'AlamofireNetworkActivityIndicator', '~> 2.4' ``` to my podfile, then ran pod install

## What did you expect to happen?

I expect to install alamofire network activity indicator to use in my project

## What happened instead?

Got an error, here is the output
```
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In snapshot (Podfile.lock):
    Alamofire (= 5.0.0-rc.3, ~> 5.0.0-rc.3)

  In Podfile:
    Alamofire (~> 5.0.0-rc.3)

    AlamofireNetworkActivityIndicator (~> 2.4) was resolved to 2.4.0, which depends on
      Alamofire (~> 4.8)
```

## Alamofire Environment

**Alamofire version:  5.0.0-rc.3**
**AlamofireNetworkActivityIndicator: 2.4**
**Xcode version:  Version 11.3 (11C29)**
**Swift version: 5**
**macOS version running Xcode: 10.15.2(19C57)**

**Comment by jshier** [comment]
Yes, to use Alamofire 5 and AlamofireNetworkActivityIndicator, you must use version 3.0.0-beta.3.
