### ISSUE TITLE
Error installing with Swift Package Manager

### ISSUE THREAD

**Issue by dcarra01** [Alamofire/AlamofireNetworkActivityIndicator#64]
## What did you do?
I tried to install from SPM with and without Alamofire 5.0.2 installed

## What did you expect to happen?
The package installed  

## What happened instead?

Xcode shows me this error:

Showing All Messages
: terminated(128): /Applications/Xcode.app/Contents/Developer/usr/bin/git -C /Users/diego/Library/Developer/Xcode/DerivedData/TestAlamofire-gvqycjnmlwcnmvfowrhyoettyohc/SourcePackages/checkouts/AlamofireNetworkActivityIndicator submodule update --init --recursive output:
    fatal: No url found for submodule path 'Carthage/Checkouts/Alamofire' in .gitmodules
    

## Alamofire Environment

**Alamofire version: 5.0.2
**AlamofireNetworkActivityIndicator: 3.0.0
**Xcode version: 11.3.1 (11C504)
**Swift version: 5.1
**macOS version running Xcode: 10.15.3 (19D76)

## Demo Project

Create a new empty project and try to install AlamofireNetworkActivityIndicator from SPM with or without Alamofire installed will show this error:

<img width="736" alt="Captura de pantalla 2020-02-24 a las 13 30 58" src="https://user-images.githubusercontent.com/18664303/75152718-ff6ee000-5709-11ea-8dcc-3284f1b1e410.png">

**Comment by jshier** [comment]
I can reproduce this, seems that SPM is trying to checkout our submodules. I've pushed a fix to `master` and will get a release out soon.

**Comment by bmatthys** [comment]
Any update on when this will be released? 🤔

**Comment by jshier** [comment]
This has been released in 3.0.1.
