### ISSUE TITLE
[SPM] Error resolving version 3.1.0 - missing macos platform - incompatible with Alamofire v5

### ISSUE THREAD

**Issue by hervouinc** [Alamofire/AlamofireNetworkActivityIndicator#71]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireNetworkActivityIndicator/blob/master/CONTRIBUTING.md).

## What did you do?

Resolving and building `Alamofire` & `AlamofireNetworkActivityIndicator` with SPM, using the following package.swift:
```
import PackageDescription

let package = Package(
    name: "Networking",
    platforms: [
        .iOS(.v11),
        .macOS(.v10_12)
    ],
    products: [
        .library(
            name: "Networking",
            targets: ["Networking"]),
    ],
    dependencies: [
        .package(url: "https://github.com/Alamofire/Alamofire.git", .exact("5.1.0")),
        .package(url: "https://github.com/Alamofire/AlamofireNetworkActivityIndicator.git", .exact("3.1.0"))
    ],
    targets: [
        .target(
            name: "Networking",
            dependencies: [
                "Alamofire",
                "AlamofireNetworkActivityIndicator"],
            path: "Sources",
    ]
)
```

## What did you expect to happen?

Both Alamofire & AlamofireNetworkActivityIndicator get resolved and built with command line:
```
swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"
```

## What happened instead?

I get this error:

> error: the library 'AlamofireNetworkActivityIndicator' requires macos 10.10, but depends on the product 'Alamofire' which requires macos 10.12; consider changing the library 'AlamofireNetworkActivityIndicator' to require macos 10.12 or later, or the product 'Alamofire' to require macos 10.10 or earlier.

What about adding the platform `.macOS(.v10_12)` to  `package.swift` ?

## Alamofire Environment

**Alamofire version: 5.1.0**
**AlamofireNetworkActivityIndicator: 3.1.0**
**Xcode version: 13.0**
**Swift version: 5.5**
**macOS version running Xcode: 11.6**

## Demo Project

-

**Comment by jshier** [comment]
Your build command is incorrect and is trying to build for macOS. You should use `xcodebuild` to build a Swift package for iOS. This library doesn't support macOS at all and so any minimum version is wrong, so we shouldn't update the package.
